[build.environment]
NODE_VERSION = "20"
RUSTUP_HOME = "$HOME/.rustup"
CARGO_HOME = "$HOME/.cargo"

[build]
command = """
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
. $CARGO_HOME/env && \
rustup default stable && \
yarn build
"""
commandOrigin = "config"
publish = "dist"
publishOrigin = "config"

[build.processing]
skip_processing = true